### ISSUE TITLE
discord down ?

### ISSUE THREAD

**Issue by letsruletheworld** [Ultrawipf/OpenFFBoard#105]
the link to discord is expired - is discord still active ?!

**Comment by tinyboxxx** [comment]
please try this and welcome~~
https://discord.gg/openffboard-704355326291607614

**Comment by Ultrawipf** [comment]
The original invite from the readme should be still active.
According to discord the code is still valid and not expired and i can use it.
If you found an expired link please let me know which one and where so if its an official place i can fix it.
But the discord community link above is also fine. Both should not expire.
