### ISSUE TITLE
Sudden loss of force feedback

### ISSUE THREAD

**Issue by arilink** [Ultrawipf/OpenFFBoard#23]
Because the multi-axis firmware supports more types of force feedback, I changed the firmware to a multi-axis firmware, but this firmware is not stable enough. When the power setting is not large, the force feedback is often lost and it will not be automatic recovery can only be manually restarted. How to solve this problem?

**Comment by Ultrawipf** [comment]
Its an active development branch. It is not stable and not intended for actual use yet but getting close. 
But i have not seen this problem yet. You might have used a broken commit and its caused by a different rtos related problem.
