### ISSUE TITLE
Please switch to makefile

### ISSUE THREAD

**Issue by Kezii** [Ultrawipf/OpenFFBoard#3]
IDK what build system you are targeting, please switch to some kind of standard like make or cmake

**Comment by Ultrawipf** [comment]
Its being developed using the STM32Cube system so its using a project file you can import using the free STM32CubeIDE and build directly. That works very well. 
But i agree a makefile might be a compatible alternative for platform independent build systems.

Not sure if there is an easy way to convert the project to a makefile and if it builds and can stay up to date. You are welcome to try it. It has to stay compatible with the CubeIDE system so a full change won't be feasable.
