### ISSUE TITLE
First Try

### ISSUE THREAD

**Issue by vtrx-az** [Ultrawipf/OpenFFBoard#51]
I compiled using Cube.
I have the STM Discovery card (STM32F407), is the firmware compatible?
I loaded the hexadecimal on the board, Windows installed the drivers and recognized the board, but in the Joystick manager it does not appear.
Something is missing?

**Comment by felixmxr** [comment]
Pin PA9 needs to be pulled high (3.3v) to activate USB functionality.
Does the debugger connection work on your board?

**Comment by vtrx-az** [comment]
STM Discovery card PA9 is at a high level.
As I mentioned, Windows installed and recognized it as a FFB device, but in the device manager the Joystick does not appear.
Is there any further configuration needed?

**Comment by vtrx-az** [comment]
Solved.
it is necessary to use the configurator.
