### ISSUE TITLE
F1 2018 doesn't detect the wheel

### ISSUE THREAD

**Issue by Flink22** [Ultrawipf/OpenFFBoard#71]
Might not be possible to get it working with f1 2018, I think the new wheels must be implemented by codemasters in the game, it has a list of compatible wheels

**Comment by Ultrawipf** [comment]
I can't test this myself, i can only comment on F1 2020 where it does work but it behaves mostly like a gamepad (in corners the virtual wheel moves under force) compared to wheels officially in their supported list.
Unfortunately i was not able to find a list of supported devices in the game files. With the dirt games you can manually add unsupported wheels but it seems like in F1 not so thats something where Codemasters would need to act and i doubt they will do any more updates for older games.
